// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ValasztasokWeb.Models;

#nullable disable

namespace ValasztasokWeb.Migrations
{
    [DbContext(typeof(ValasztasDbContext))]
    partial class ValasztasDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("ValasztasokWeb.Models.Jelolt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Kerulet")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nev")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PartRovidNev")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SzavazatokSzama")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PartRovidNev");

                    b.ToTable("JeloltekListaja");
                });

            modelBuilder.Entity("ValasztasokWeb.Models.Part", b =>
                {
                    b.Property<string>("RovidNev")
                        .HasColumnType("TEXT");

                    b.Property<string>("TeljesNev")
                        .HasColumnType("TEXT");

                    b.HasKey("RovidNev");

                    b.ToTable("Partok");
                });

            modelBuilder.Entity("ValasztasokWeb.Models.Jelolt", b =>
                {
                    b.HasOne("ValasztasokWeb.Models.Part", "Part")
                        .WithMany("Jeloltek")
                        .HasForeignKey("PartRovidNev")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Part");
                });

            modelBuilder.Entity("ValasztasokWeb.Models.Part", b =>
                {
                    b.Navigation("Jeloltek");
                });
#pragma warning restore 612, 618
        }
    }
}
